TEMPLATEROOT = ..

# compilation flags for gdb

CFLAGS  = -O0 -g3
ASFLAGS = -g3

# object files

OBJS= dht22.o stupid_delay.o main.o ssd1306.o ssd1306_fonts.o $(STARTUP) $(HAL_COMPILE)

# include common make file

include $(TEMPLATEROOT)/Makefile.common
